"""Shared memory subsystem scaffolding for future Jade runtime work."""

from app.memory.interfaces import (
    ConversationCompactor,
    LongTermMemoryBackend,
    MemoryRetriever,
    SessionMemoryBackend,
)
from app.memory.long_term import (
    LONG_TERM_MEMORY_INDEX_BASENAME,
    LongTermMemoryFormatError,
    load_long_term_memory_catalog,
    load_long_term_memory_file,
    resolve_long_term_memory_index_file,
)
from app.memory.paths import (
    MemorySubsystemPaths,
    build_memory_subsystem_paths,
    resolve_compaction_dir,
    resolve_long_term_memory_dir,
    resolve_long_term_memory_index_path,
    resolve_memory_work_dir,
    resolve_retrieval_dir,
    resolve_session_memory_store_path,
)
from app.memory.types import (
    ConversationCompactionRequest,
    ConversationCompactionSummary,
    LongTermMemoryCatalog,
    LongTermMemoryFile,
    LongTermMemoryFrontmatter,
    LongTermMemoryRecord,
    LongTermMemoryType,
    MemoryReference,
    MemoryRetrievalQuery,
    MemoryRetrievalResult,
    MemoryScope,
    SessionMemorySnapshot,
)

__all__ = [
    "ConversationCompactionRequest",
    "ConversationCompactionSummary",
    "ConversationCompactor",
    "LONG_TERM_MEMORY_INDEX_BASENAME",
    "LongTermMemoryBackend",
    "LongTermMemoryCatalog",
    "LongTermMemoryFile",
    "LongTermMemoryFormatError",
    "LongTermMemoryFrontmatter",
    "LongTermMemoryRecord",
    "LongTermMemoryType",
    "MemoryReference",
    "MemoryRetriever",
    "MemoryRetrievalQuery",
    "MemoryRetrievalResult",
    "MemoryScope",
    "MemorySubsystemPaths",
    "SessionMemoryBackend",
    "SessionMemorySnapshot",
    "build_memory_subsystem_paths",
    "load_long_term_memory_catalog",
    "load_long_term_memory_file",
    "resolve_compaction_dir",
    "resolve_long_term_memory_dir",
    "resolve_long_term_memory_index_file",
    "resolve_long_term_memory_index_path",
    "resolve_memory_work_dir",
    "resolve_retrieval_dir",
    "resolve_session_memory_store_path",
]
